/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M8.15 4.52l3.18 5.51L5 21l-3-5.5zM13.2 15.5c-.13.48-.2.98-.2 1.5 0 1.54.58 2.94 1.54 4H6.73l3.17-5.5zM20 13v3h3v2h-3v3h-2v-3h-3v-2h3v-3zM15 3l4.49 8.02c-.16-.01-.32-.02-.49-.02-1.7 0-3.23.71-4.32 1.84L9 3z",
    },
  ],
  circles: [],
};

export const AddToDriveIcon = (props: IconProps) => renderIcon(props, iconType);
