/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M11.64 15.36c.2-.2.51-.2.71 0l2.79 2.79c.32.31.1.85-.35.85H13v2c0 .55-.45 1-1 1l-.1162-.0068C11.388 21.9352 11 21.5107 11 21v-2H9.21c-.45 0-.67-.54-.36-.85zM19 12c.55 0 1 .45 1 1l-.0068.1162C19.9352 13.612 19.5107 14 19 14H5c-.55 0-1-.45-1-1l.0068-.1162C4.0648 12.388 4.4893 12 5 12zm0-3c.55 0 1 .45 1 1l-.0068.1162C19.9352 10.612 19.5107 11 19 11H5c-.55 0-1-.45-1-1l.0068-.1162C4.0648 9.388 4.4893 9 5 9zm-7-8 .1162.0068C12.612 1.0648 13 1.4893 13 2v2h1.79c.45 0 .67.54.35.85l-2.79 2.79c-.2.2-.51.2-.71 0L8.85 4.85c-.31-.31-.09-.85.36-.85H11V2c0-.55.45-1 1-1",
    },
  ],
  circles: [],
};

export const CompressIcon = (props: IconProps) => renderIcon(props, iconType);
