/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M14 20c0 1.1-.9 2-2 2s-2-.9-2-2zm1-3c.55 0 1 .45 1 1l-.0068.1162C15.9352 18.612 15.5107 19 15 19H9c-.55 0-1-.45-1-1l.0068-.1162C8.0648 17.388 8.4893 17 9 17zM12 2c4.14 0 7.5 3.36 7.5 7.5 0 3.82-2.66 5.86-3.77 6.5H8.27c-1.11-.64-3.77-2.68-3.77-6.5C4.5 5.36 7.86 2 12 2",
    },
  ],
  circles: [],
};

export const LightbulbIcon = (props: IconProps) => renderIcon(props, iconType);
