/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M18 13c2.76 0 5 2.24 5 5s-2.24 5-5 5-5-2.24-5-5 2.24-5 5-5M12 1c2.76 0 5 2.24 5 5v2h1c1.1 0 2 .9 2 2v1.29c-.63-.19-1.3-.29-2-.29-3.87 0-7 3.13-7 7 0 1.49.47 2.87 1.26 4H6c-1.1 0-2-.9-2-2V10c0-1.1.9-2 2-2h1V6c0-2.76 2.24-5 5-5m5.99 14-.0909.008c-.2353.0416-.4091.2431-.4091.492V18c0 .13.06.26.15.35L19.29 20c.2.2.51.2.71 0s.2-.51-.01-.71l-1.5-1.5V15.5c0-.28-.22-.5-.5-.5M12 3c-1.66 0-3 1.34-3 3v2h6V6c0-1.66-1.34-3-3-3",
    },
  ],
  circles: [],
};

export const LockClockIcon = (props: IconProps) => renderIcon(props, iconType);
