/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M11 3c.55 0 1 .45 1 1l-.0068.1162C11.9352 4.612 11.5107 5 11 5H5v14h6c.55 0 1 .45 1 1l-.0068.1162C11.9352 20.612 11.5107 21 11 21H5c-1.1 0-2-.9-2-2V5c0-1.1.9-2 2-2zm6 6.21c0-.45.54-.67.86-.35l2.79 2.79c.19.19.19.51-.01.7l-2.79 2.79c-.31.32-.85.1-.85-.35V13h-7c-.55 0-1-.45-1-1l.0068-.1162C9.0648 11.388 9.4893 11 10 11h7z",
    },
  ],
  circles: [],
};

export const LogoutIcon = (props: IconProps) => renderIcon(props, iconType);
