/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M12 2c5.52 0 10 4.48 10 10s-4.48 10-10 10S2 17.52 2 12 6.48 2 12 2M5.69 7.1C4.63 8.45 4 10.15 4 12c0 1.95.7 3.73 1.86 5.12C7.55 15.8 9.68 15 12 15q.885 0 1.74.15l-2.2-2.2c-1.56-.2-2.78-1.43-2.99-2.99zM12 4c-1.85 0-3.55.63-4.9 1.69L18.31 16.9C19.37 15.54 20 13.85 20 12c0-4.42-3.58-8-8-8m0 2c1.93 0 3.5 1.57 3.5 3.5 0 .52-.12 1-.32 1.44l-4.62-4.62C11 6.12 11.48 6 12 6",
    },
  ],
  circles: [],
};

export const NoAccountsIcon = (props: IconProps) => renderIcon(props, iconType);
