/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M17 12c2.76 0 5 2.24 5 5s-2.24 5-5 5-5-2.24-5-5 2.24-5 5-5zM3 5.51c0-.72.73-1.2 1.39-.93l12.89 5.43c-.09 0-.18-.01-.28-.01-3.86 0-7 3.14-7 7v.05l-5.61 2.36c-.66.28-1.39-.2-1.39-.92v-3.71c0-.46.31-.86.76-.97L11 12l-7.24-1.81c-.45-.11-.76-.51-.76-.97zM16.99 14l-.0909.008c-.2353.0416-.4091.2431-.4091.492V17c0 .13.06.26.15.35L18.29 19c.2.2.51.2.7 0l.0593-.0704c.1382-.1971.1185-.4618-.0593-.6396l-1.5-1.5V14.5c0-.28-.22-.5-.5-.5z",
    },
  ],
  circles: [],
};

export const ScheduleSendIcon = (props: IconProps) =>
  renderIcon(props, iconType);
