/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M17 12c2.76 0 5 2.24 5 5s-2.24 5-5 5-5-2.24-5-5 2.24-5 5-5M3 4l14.28 6.01c-.09 0-.18-.01-.28-.01-3.87 0-7 3.13-7 7v.05L3 20v-6l8-2-8-2zm14 10c-.28 0-.5.22-.5.5V17h-1.29c-.45 0-.67.54-.35.85l1.79 1.79c.2.2.51.2.71 0l1.79-1.79c.31-.31.09-.85-.36-.85H17.5v-2.5c0-.28-.22-.5-.5-.5",
    },
  ],
  circles: [],
};

export const SendAndArchiveIcon = (props: IconProps) =>
  renderIcon(props, iconType);
