/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M14.99 3c1.1 0 2 .9 2 2v9.99c0 .53-.21 1.04-.58 1.41l-5.53 5.54c-.29.29-.68.44-1.06.44s-.76-.14-1.05-.43c-.36-.36-.51-.87-.41-1.37L9.31 16H3.66c-2.15 0-3.6-2.2-2.75-4.18l3.26-7.61C4.48 3.48 5.2 3 6 3zm0 2H6l-3.25 7.6c-.19.44-.03.78.08.95s.36.45.83.45h8.11l-.5 2.41-.61 2.92 4.33-4.34zM21 3c1.1 0 2 .9 2 2v8c0 1.1-.9 2-2 2s-2-.9-2-2V5c0-1.1.9-2 2-2",
    },
  ],
  circles: [],
};

export const ThumbDownOffAltIcon = (props: IconProps) =>
  renderIcon(props, iconType);
