/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "m10.9711 14.5489-3.3327 5.7748h11.0281L22 14.5489zm10.0832-1.6371L15.3331 3h-6.667l5.722 9.9118zM7.7191 4.6407 2 14.5489l3.3335 5.7748 5.719-9.9083z",
      fillRule: "evenodd",
    },
  ],
  circles: [],
};

export const GoogleDriveIcon = (props: IconProps) =>
  renderIcon(props, iconType);
