/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M6.5443 8.211v12.9036H2.2474V8.2109zm.2734-3.9844q.013.9505-.6575 1.5885t-1.7644.638h-.026q-1.0677 0-1.7188-.638T2 4.2266q0-.9635.6706-1.595Q3.341 2 4.4219 2t1.7317.6315.6641 1.595M22 13.7187v7.3959h-4.2839v-6.901q0-1.3673-.5273-2.142t-1.6471-.7747q-.8204 0-1.3737.4492-.5535.4492-.8269 1.1133-.1432.3906-.1432 1.0547v7.2005H8.9141q.026-5.1953.026-8.4245t-.013-3.8542l-.013-.625h4.2838v1.875h-.026q.2604-.4166.5338-.7291t.7357-.6771 1.1328-.5664 1.4909-.2018q2.2266 0 3.5807 1.4778Q22 10.8673 22 13.7187",
      fillRule: "evenodd",
    },
  ],
  circles: [],
};

export const LinkedinIcon = (props: IconProps) => renderIcon(props, iconType);
