/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M2.0073 11.3333 2 4.832l8-1.0867v7.588zm9.326-7.7813L21.9973 2v9.3333h-10.664zM22 12.6667 21.9973 22l-10.664-1.5v-7.8333zM10 20.33l-7.9933-1.096-.0007-6.5673H10z",
      fillRule: "evenodd",
    },
  ],
  circles: [],
};

export const Windows8Icon = (props: IconProps) => renderIcon(props, iconType);
