module.exports = {
  floatPrecision: 4,
  plugins: [
    { name: 'removeDoctype' },
    { name: 'removeXMLProcInst' },
    { name: 'removeComments' },
    { name: 'removeMetadata' },
    { name: 'removeEditorsNSData' },
    { name: 'cleanupAttrs' },
    { name: 'minifyStyles' },
    { name: 'cleanupIds' },
    { name: 'removeUselessDefs' },
    { name: 'cleanupNumericValues' },
    { name: 'convertColors' },
    { name: 'removeUnknownsAndDefaults' },
    { name: 'removeNonInheritableGroupAttrs' },
    {
      name: 'removeUselessStrokeAndFill',
      params: {
        removeNone: true,
      },
    },
    { name: 'cleanupEnableBackground' },
    { name: 'removeHiddenElems' },
    { name: 'removeEmptyText' },
    { name: 'convertShapeToPath' },
    { name: 'moveElemsAttrsToGroup' },
    { name: 'moveGroupAttrsToElems' },
    { name: 'collapseGroups' },
    { name: 'convertPathData' },
    { name: 'convertTransform' },
    { name: 'removeEmptyAttrs' },
    { name: 'removeEmptyContainers' },
    { name: 'removeUnusedNS' },
    { name: 'mergePaths' },
    { name: 'sortAttrs' },
    { name: 'removeTitle' },
    { name: 'removeDesc' },
    { name: 'removeXMLNS' },
    { name: 'convertStyleToAttrs' },
    { name: 'cleanupListOfValues' },
    { name: 'removeRasterImages' },
    { name: 'removeDimensions' },
    { name: 'removeElementsByAttr' },
    { name: 'removeStyleElement' },
    { name: 'removeScriptElement' },
  ],
};