/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M20 2c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2zm-9 5H7.65c-1.1 0-2 .9-2 2v2.45c-.4.46-.65 1.06-.65 1.72v3.08c0 .41.34.75.75.75l.1009-.007c.3634-.0502.6491-.3672.6491-.743v-.75h11v.75c0 .41.34.75.75.75l.1009-.007c.3634-.0502.6491-.3672.6491-.743v-3.08c0-.66-.25-1.26-.65-1.72V9c0-1.1-.9-2-2-2H13c-.37 0-.72.12-1 .32-.28-.2-.63-.32-1-.32zm5.5 5c.55 0 1 .45 1 1v1h-11v-1c0-.55.45-1 1-1zm-5.25-3.5v2h-4v-2zm5.5 0v2h-4v-2z",
    },
  ],
  circles: [],
};

export const BedroomParentIcon = (props: IconProps) =>
  renderIcon(props, iconType);
