/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M20 2c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2zm-5.5 5h-5c-1.1 0-2 .9-2 2v1.67c-.88.35-1.5 1.2-1.5 2.2v3.38c0 .41.34.75.75.75l.1009-.007c.3634-.0502.6491-.3672.6491-.743v-.75h9v.75c0 .41.34.75.75.75l.1009-.007c.3634-.0502.6491-.3672.6491-.743v-3.38c0-1-.62-1.85-1.5-2.2V9c0-1.1-.9-2-2-2zm1.14 5c.48 0 .87.39.87.87V14h-9v-1.13H7.5c0-.48.39-.87.87-.87zM15 8.5v2H9v-2z",
    },
  ],
  circles: [],
};

export const BedroomChildIcon = (props: IconProps) =>
  renderIcon(props, iconType);
