/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M19 2c.55 0 1 .45 1 1l-.0068.1162C19.9352 3.612 19.5107 4 19 4h-1v2c0 .55-.45 1-1 1H9c-.55 0-1-.45-1-1V4H6v16h4.03C8.81 19.09 8 17.64 8 16v-3c0-1.1.9-2 2-2h6c1.1 0 2 .9 2 2v3c0 1.64-.8 3.09-2.03 4H19c.55 0 1 .45 1 1l-.0068.1162C19.9352 21.612 19.5107 22 19 22H6c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2zm-6 6c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1z",
    },
  ],
  circles: [],
};

export const CoffeeMakerIcon = (props: IconProps) =>
  renderIcon(props, iconType);
