/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M8 19c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1m4 0c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1m4 0c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1m-8-3c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1m4 0c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1m4 0c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1M12 3l.1162.0068C12.612 3.0648 13 3.4893 13 4v1.08c3.39.49 6 3.39 6 6.92v1c0 .55-.45 1-1 1H6c-.55 0-1-.45-1-1v-1c0-3.53 2.61-6.43 6-6.92V4c0-.55.45-1 1-1",
    },
  ],
  circles: [],
};

export const ShowerIcon = (props: IconProps) => renderIcon(props, iconType);
