/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M20 2H4c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2m0 9h-7V4h7zm-9-7v7H4V4zm-7 9h7v7H4zm9 7v-7h7v7z",
    },
  ],
  circles: [],
};

export const WindowIcon = (props: IconProps) => renderIcon(props, iconType);
