/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M8 8c.55 0 1 .45 1 1l-.0068.1162C8.9352 9.612 8.5107 10 8 10H6v11h12V10h-2c-.55 0-1-.45-1-1l.0068-.1162C15.0648 8.388 15.4893 8 16 8h2c1.1 0 2 .9 2 2v11c0 1.1-.9 2-2 2H6c-1.1 0-2-.9-2-2V10c0-1.1.9-2 2-2zm3.64-6.64c.2-.2.51-.2.71 0l2.79 2.79c.32.31.1.85-.35.85H13v10c0 .55-.45 1-1 1l-.1162-.0068C11.388 15.9352 11 15.5107 11 15V5H9.21c-.45 0-.67-.54-.36-.85z",
    },
  ],
  circles: [],
};

export const IosShareIcon = (props: IconProps) => renderIcon(props, iconType);
