/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "m3.02 15.62 5.36 5.36c-2.41.09-4.34-.32-4.69-.67s-.75-2.27-.67-4.69M13.08 3.28l7.63 7.63c-.42 2.33-1.35 4.78-3.18 6.62s-4.28 2.77-6.62 3.18l-7.63-7.63c.42-2.33 1.35-4.78 3.18-6.62s4.29-2.76 6.62-3.18M14.8 9.2a.984.984 0 0 0-1.4 0l-4.2 4.2c-.39.39-.39 1.01 0 1.4s1.01.39 1.4 0l4.2-4.2c.39-.39.39-1.01 0-1.4m.82-6.18c2.41-.09 4.34.32 4.69.67s.75 2.27.67 4.69Z",
      fillRule: "evenodd",
    },
  ],
  circles: [],
};

export const SportsFootballIcon = (props: IconProps) =>
  renderIcon(props, iconType);
