/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "m17 16.04 3.11 1.8C18.29 20.35 15.34 22 12 22c-1.4 0-2.72-.29-3.93-.8zm-5-2.89 3 1.74-8.93 5.14c-.84-.61-1.57-1.36-2.18-2.2zM6 4.01v10.3l-3.11 1.8C2.32 14.85 2 13.46 2 12c0-3.27 1.58-6.16 4-7.99m7 3.95 8.93 5.16c-.12 1.05-.4 2.05-.82 2.98L13 11.42zm-2-5.91v9.37l-3 1.74V2.84c.93-.41 1.94-.68 3-.79m2 0c4.66.46 8.37 4.13 8.92 8.76L13 5.65Z",
      fillRule: "evenodd",
    },
  ],
  circles: [],
};

export const SportsVolleyballIcon = (props: IconProps) =>
  renderIcon(props, iconType);
