/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M3.18 13.72c.2-.38.75-.35.91.05l1.4 3.49-1.05.52c-.95.47-2.09.07-2.38-.94-.11-.41-.07-.83.12-1.19zm16.73.04c.16-.39.71-.42.91-.04l1 1.93c.19.36.23.78.12 1.18-.29 1.01-1.44 1.41-2.38.94l-1.05-.52zm-3.68-4.84c.06-.67.75-1.09 1.37-.84l1.17.47c.77.3 1.14 1.18.83 1.95L17 17h-1.51zM6.4 8.08c.62-.25 1.3.17 1.36.84L8.5 17H7l-2.6-6.5c-.31-.77.06-1.65.83-1.95zM13.36 6c.88 0 1.57.76 1.49 1.63L14 16.99h-4l-.85-9.35C9.07 6.76 9.76 6 10.65 6z",
    },
  ],
  circles: [],
};

export const BakeryDiningIcon = (props: IconProps) =>
  renderIcon(props, iconType);
