/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M17 5c1.1 0 2 .9 2 2v2.65c0 .45-.15.89-.44 1.25l-3.48 4.35c-.38.47-.95.75-1.56.75H10c0 1.66-1.34 3-3 3s-3-1.34-3-3H3c-.55 0-1-.45-1-1v-2c0-2.21 1.79-4 4-4h3c.55 0 1 .45 1 1v4h3.52L17 9.65V7h-2c-.55 0-1-.45-1-1l.0068-.1162C14.0648 5.388 14.4893 5 15 5zm2 8c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3M8 16H6c0 .55.45 1 1 1s1-.45 1-1m11-1c-.55 0-1 .45-1 1s.45 1 1 1 1-.45 1-1-.45-1-1-1M9 6c.5107 0 .9352.388.9932.8838L10 7c0 .55-.45 1-1 1H6c-.5107 0-.9352-.388-.9932-.8838L5 7c0-.55.45-1 1-1z",
    },
  ],
  circles: [],
};

export const DeliveryDiningIcon = (props: IconProps) =>
  renderIcon(props, iconType);
