/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M20.8 19c.44 0 .66.54.35.85l-1 1c-.09.1-.22.15-.35.15H4.21c-.14 0-.26-.05-.36-.15l-1-1c-.31-.31-.09-.85.36-.85zM9.75 3C10.99 3 12 4.01 12 5.25h8.25c.41 0 .75.34.75.75s-.34.75-.75.75H12l-.0052.1537C11.9154 8.0724 10.9383 9 9.75 9H8v6.08c.48.09.94.24 1.35.47.79-2.07 2.79-3.55 5.14-3.55 3.2 0 5.77 2.74 5.48 6H3c.22-.61.56-1.15 1-1.61V9h-.25C3.34 9 3 8.66 3 8.25s.34-.75.75-.75H4v-.75h-.25C3.34 6.75 3 6.41 3 6s.34-.75.75-.75H4V4.5h-.25c-.41 0-.75-.34-.75-.75S3.34 3 3.75 3zM6.5 9h-1v6.36c.32-.13.65-.24 1-.3zM10 6.75H8v.75h2zm-3.5 0h-1v.75h1zM10 4.5H8v.75h2zm-3.5 0h-1v.75h1z",
    },
  ],
  circles: [],
};

export const DinnerDiningIcon = (props: IconProps) =>
  renderIcon(props, iconType);
