/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M12 2c.9 0 1.78.16 2.61.44L9.29 7.76c-.18.18-.29.44-.29.7V12c0 .55.45 1 1 1h3.54c.26 0 .52-.11.7-.29l5.31-5.31c.29.86.45 1.79.45 2.8 0 3.17-2.44 6.92-7.33 11.22-.38.33-.96.33-1.34 0C6.44 17.12 4 13.38 4 10.2 4 5.22 7.8 2 12 2m5.16.72 2.12 2.12L13.12 11H11V8.88zm1.43-1.43c.39-.39 1.02-.39 1.41 0l.71.71c.39.39.39 1.02 0 1.41l-.72.72-2.12-2.12z",
    },
  ],
  circles: [],
};

export const EditLocationEditIcon = (props: IconProps) =>
  renderIcon(props, iconType);
