/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "m11 18 6 3h-4v2l-6-3h4zm4.06-15c.6 0 1.16.26 1.54.72l3.94 4.72c.3.36.46.81.46 1.28v1.46c1.16.42 2 1.52 2.01 2.82 0 1.66-1.34 3-3 3-1.31 0-2.41-.84-2.82-2H8.82C8.4 16.16 7.3 17 6 17s-2.4-.84-2.82-2H3c-1.1 0-2-.9-2-2V5c0-1.1.9-2 2-2zM6 13c-.55 0-1 .45-1 1s.45 1 1 1 1-.45 1-1-.45-1-1-1m14 0c-.55 0-1 .45-1 1s.45 1 1 1 1-.45 1-1-.45-1-1-1m-7-8H9v4h2c.55 0 1 .45 1 1l-.0068.1162C11.9352 10.612 11.5107 11 11 11H9v2h5V6c0-.55-.45-1-1-1m3 1.12V9h2.4zM7 5H4c-.55 0-1 .45-1 1v3h4z",
    },
  ],
  circles: [],
};

export const ElectricRickshawIcon = (props: IconProps) =>
  renderIcon(props, iconType);
