/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M15 13v7c0 .55-.45 1-1 1h-4c-.55 0-1-.45-1-1v-7zM13 3c1.1 0 2 .9 2 2v1l2.59-2.59c.26-.26.62-.41.99-.41h.01c.78 0 1.41.63 1.41 1.41v5.18c0 .78-.63 1.41-1.4 1.41h-.01c-.38 0-.74-.15-1-.41L15 8v3H9V8H4c0-2.76 2.24-5 5-5z",
    },
  ],
  circles: [],
};

export const HardwareIcon = (props: IconProps) => renderIcon(props, iconType);
