/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M2.0007 6.9098C2.0312 4.9494 3.1017 2.6755 11.66 3.03c-.16.36-1.14 2.37-.37 4.97H4v3h9.11c1.26 1.24 2.98 2 4.89 2v3.5c0 1.93-1.57 3.5-3.5 3.5l1.21.81c.18.12.29.32.29.54l-.007.0963A.6486.6486 0 0115.35 22H4.65c-.36 0-.65-.29-.65-.65l.009-.108a.6477.6477 0 01.281-.432L5.5 20C3.57 20 2 18.43 2 16.5zM10 14c-.83 0-1.5.67-1.5 1.5S9.17 17 10 17s1.5-.67 1.5-1.5S10.83 14 10 14zm8-13c2.76 0 5 2.24 5 5s-2.24 5-5 5-5-2.24-5-5 2.24-5 5-5zm0 7c-.28 0-.5.22-.5.5s.22.5.5.5.5-.22.5-.5-.22-.5-.5-.5zm0-5c-.28 0-.5.22-.5.5v3c0 .28.22.5.5.5s.5-.22.5-.5v-3c0-.28-.22-.5-.5-.5z",
    },
  ],
  circles: [],
};

export const RailwayAlertIcon = (props: IconProps) =>
  renderIcon(props, iconType);
