/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M18.7 11.55l-.49 6.6c-.07 1.04-.94 1.85-1.99 1.85H7.79c-1.05 0-1.92-.81-2-1.85l-.49-6.6zM14.15 3c.53 0 1.04.21 1.42.59l3.46 3.48-.03.56.89-.88c.39-.39 1.01-.39 1.4 0s.38 1.03-.02 1.41L19.35 10H4.66L2.72 8.13c-.4-.38-.4-1.01-.02-1.4l.02-.02c.38-.39 1-.39 1.39-.01l.89.87-.03-.5 3.46-3.48c.38-.38.89-.59 1.42-.59z",
    },
  ],
  circles: [],
};

export const TakeoutDiningIcon = (props: IconProps) =>
  renderIcon(props, iconType);
