/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M6 16c1.1046 0 2 .8954 2 2s-.8954 2-2 2-2-.8954-2-2 .8954-2 2-2zm10.96-4.1l2.12 2.12-5.83 5.83c-.09.1-.22.15-.35.15h-1.4c-.28 0-.5-.22-.5-.5v-1.43c0-.13.05-.26.15-.36zM6 10c1.1046 0 2 .8954 2 2s-.8954 2-2 2-2-.8954-2-2 .8954-2 2-2zm6 0c1.1 0 2 .9 2 2v.03L12.03 14H12c-1.1 0-2-.9-2-2s.9-2 2-2zm6.73.15c.2-.2.51-.2.71 0l1.41 1.41c.2.2.2.51 0 .71l-1.06 1.06-2.12-2.12zM12 4c1.1046 0 2 .8954 2 2s-.8954 2-2 2-2-.8954-2-2 .8954-2 2-2zM6 4c1.1046 0 2 .8954 2 2s-.8954 2-2 2-2-.8954-2-2 .8954-2 2-2zm12 0c1.1046 0 2 .8954 2 2s-.8954 2-2 2-2-.8954-2-2 .8954-2 2-2z",
    },
  ],
  circles: [],
};

export const AppRegistrationIcon = (props: IconProps) =>
  renderIcon(props, iconType);
