/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M20 4c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2zM9.25 9H6c-.55 0-1 .45-1 1v1.75c0 .55.45 1 1 1h2.5v.75H5.75c-.41 0-.75.34-.75.75l.007.1009c.0502.3634.3672.6491.743.6491H9c.55 0 1-.45 1-1v-1.75c0-.55-.45-1-1-1H6.5v-.75h2.75c.41 0 .75-.34.75-.75S9.66 9 9.25 9M12 9l-.1162.0068C11.388 9.0648 11 9.4893 11 10v4c0 .55.45 1 1 1l.1162-.0068C12.612 14.9352 13 14.5107 13 14v-4c0-.55-.45-1-1-1m6 0h-3c-.55 0-1 .45-1 1v4.25c0 .41.34.75.75.75l.1009-.007c.3634-.0502.6491-.3672.6491-.743V13H18c.55 0 1-.45 1-1v-2c0-.55-.45-1-1-1m-.5 1.5v1h-2v-1z",
    },
  ],
  circles: [],
};

export const SipIcon = (props: IconProps) => renderIcon(props, iconType);
