/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M16 10.5q0 .203-.1483.3518l-3.5 3.5Q12.2035 14.5 12 14.5t-.3517-.1484l-3.5-3.4999Q8 10.7035 8 10.5001q0-.2036.1483-.3518T8.5001 10h6.9998q.203 0 .3518.1483t.1483.3518",
      fillRule: "evenodd",
    },
  ],
  circles: [],
};

export const ArrowDropDownIcon = (props: IconProps) =>
  renderIcon(props, iconType);
