/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M6.84 6.83c.69-.5 1.62-.5 2.32 0l5 3.57c.53.38.84.98.84 1.63V20c0 .55-.45 1-1 1h-4v-6H6v6H2c-.55 0-1-.45-1-1v-7.97c0-.65.31-1.25.84-1.63zM21.03 3C22.12 3 23 3.88 23 4.97v14.06c0 1.09-.88 1.97-1.97 1.97H17v-4h2v-2h-2v-2h2v-2h-2.13c-.24-.89-.78-1.69-1.54-2.23l-5-3.57-.24-.14-.09-.09C10 3.88 10.88 3 11.97 3zM19 7h-2v2h2z",
    },
  ],
  circles: [],
};

export const MapsHomeWorkIcon = (props: IconProps) =>
  renderIcon(props, iconType);
