/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "m5 5 .1162.0068C5.612 5.0648 6 5.4893 6 6v15h9c.55 0 1 .45 1 1l-.0068.1162C15.9352 22.612 15.5107 23 15 23H6c-1.1 0-2-.9-2-2V6c0-.55.45-1 1-1m13-4c1.1 0 2 .9 2 2v14c0 1.1-.9 2-2 2h-8c-1.1 0-2-.9-2-2V3c0-1.1.9-2 2-2zm0 4h-8v10h8zm-3.5 3.2c0-.44.54-.66.85-.35l1.29 1.29c.2.2.2.51 0 .71l-1.29 1.29c-.31.32-.85.1-.85-.35v-.54h-2v.99c0 .41-.34.75-.75.75l-.1009-.007c-.3634-.0502-.6491-.3672-.6491-.743v-1.5c0-.55.45-1 1-1h2.5z",
    },
  ],
  circles: [],
};

export const OfflineShareIcon = (props: IconProps) =>
  renderIcon(props, iconType);
