/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M17.65 9.35c.19-.19.51-.19.7.01l2.79 2.79c.32.31.1.85-.35.85H19v2c0 2.21-1.79 4-4 4h-2v1.8c0 .44-.54.66-.85.35l-2.79-2.79c-.2-.2-.2-.51 0-.71l2.79-2.79c.31-.32.85-.1.85.35V17h2c1.1 0 2-.9 2-2v-2h-1.79c-.45 0-.67-.54-.35-.86zM8 10v11H5c-1.1 0-2-.9-2-2v-9zm11-7c1.1 0 2 .9 2 2v3H10V3zM8 3v5H3V5c0-1.1.9-2 2-2z",
    },
  ],
  circles: [],
};

export const PivotTableChartIcon = (props: IconProps) =>
  renderIcon(props, iconType);
