/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M19 16c1.1 0 2 .9 2 2l-.0055.1487C20.9178 19.18 20.05 20 19 20h-8l4-4zm-6.94-8.81 3.76 3.75-8.77 8.77c-.19.18-.44.29-.71.29H4c-.55 0-1-.45-1-1v-2.34c0-.26.11-.52.29-.7zm2.9-2.9c.39-.39 1.02-.39 1.41 0l2.34 2.34c.39.39.39 1.02 0 1.41l-1.83 1.83-3.75-3.75z",
    },
  ],
  circles: [],
};

export const DriveFileRenameOutlineIcon = (props: IconProps) =>
  renderIcon(props, iconType);
