/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M18 18c.55 0 1 .45 1 1l-.0068.1162C18.9352 19.612 18.5107 20 18 20H6c-.55 0-1-.45-1-1l.0068-.1162C5.0648 18.388 5.4893 18 6 18zm.01-13.29c.39-.39 1.02-.39 1.41 0l.0852.094c.3124.3915.284.956-.0852 1.316l-9.19 9.19c-.39.39-1.02.39-1.41 0l-4.24-4.24a.9959.9959 0 010-1.41l.094-.083a.9959.9959 0 011.316.083l3.54 3.54z",
    },
  ],
  circles: [],
};

export const FileDownloadDoneIcon = (props: IconProps) =>
  renderIcon(props, iconType);
