/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 -960 960 960",
  paths: [
    {
      d: "M168-192q-29 0-50.5-21.5T96-264v-432q0-29.7 21.5-50.85Q139-768 168-768h185.64q14.35 0 27.36 5 13 5 24 16l75 75h312q29.7 0 50.85 21.15Q864-629.7 864-600v336q0 29-21.15 50.5T792-192H168zm0-72h624v-336H450l-96-96H168v432zm0 0v-432 432z",
    },
  ],
  circles: [],
};

export const FolderMaterialIcon = (props: IconProps) =>
  renderIcon(props, iconType);
