/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "m12.0314 5.4975 7.53 13.01h-15.06zm-9.26 12.01c-.77 1.33.19 3 1.73 3h15.06c1.54 0 2.5-1.67 1.73-3l-7.53-13.01c-.77-1.33-2.69-1.33-3.46 0zm8.26-7v2c0 .55.45 1 1 1s1-.45 1-1v-2c0-.55-.45-1-1-1s-1 .45-1 1m0 5h2v2h-2z",
    },
  ],
  circles: [],
};

export const WarningAmberIcon = (props: IconProps) =>
  renderIcon(props, iconType);
