/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M2.194 3.427a.9959.9959 0 011.316.083l16.96 16.97c.39.39.39 1.02 0 1.41l-.094.083a.9959.9959 0 01-1.316-.083l-6.36-6.36-6.17 6.17c-.39.39-1.02.39-1.41 0l-2.83-2.83a.9959.9959 0 010-1.41l6.17-6.17L2.1 4.93c-.39-.39-.39-1.02 0-1.42zM13.46 6.29c.39-.39 1.02-.39 1.41 0l2.83 2.83c.39.39.39 1.02 0 1.41l-2.17 2.17-1.41-1.41 1.46-1.46-1.41-1.41-1.47 1.45-1.41-1.41zM19.54 2c.18-.39.73-.39.91 0l.49 1.06 1.06.49c.39.17.39.73 0 .9l-1.05.49L20.46 6c-.18.39-.73.39-.91 0l-.49-1.05L18 4.46c-.39-.18-.39-.73 0-.91l1.05-.49z",
    },
  ],
  circles: [],
};

export const AutoFixOffIcon = (props: IconProps) => renderIcon(props, iconType);
