/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M2.1 3.51c.39-.39 1.02-.39 1.41 0l16.97 16.98c.39.39.39 1.02 0 1.41s-1.02.39-1.41 0l-.9-.9H5c-1.1 0-2-.9-2-2V5.83l-.9-.91a.9959.9959 0 010-1.41zM19 3c1.1 0 2 .9 2 2v13.17L5.83 3zM9.4 13.53c-.2-.27-.6-.27-.8 0l-2 2.67c-.25.33-.01.8.4.8h7.17l-2.1-2.1-.82 1.1z",
    },
  ],
  circles: [],
};

export const HideImageIcon = (props: IconProps) => renderIcon(props, iconType);
