/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M19.96 4.01c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2h-16c-1.1 0-2-.9-2-2v-12c0-1.1.9-2 2-2zM20 6H4v12h16zm-13.3.88c.14-.53.69-.84 1.22-.7l10.5 2.83c.53.14.85.69.72 1.22l-1.85 6.87c-.15.54-.7.85-1.23.71l-10.5-2.83c-.54-.15-.85-.7-.71-1.23z",
    },
  ],
  circles: [],
};

export const VideoStableIcon = (props: IconProps) =>
  renderIcon(props, iconType);
