/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M21 18c.55 0 1 .45 1 1s-.45 1-1 1H3c-.55 0-1-.45-1-1s.45-1 1-1zm-9-9c3.87 0 7 3.13 7 7H5c0-3.87 3.13-7 7-7m6.37-1.75c.39-.39 1.02-.39 1.41 0l.083.094a.996.996 0 0 1-.083 1.316l-.71.71c-.39.39-1.03.39-1.41 0a.996.996 0 0 1 0-1.41zM4.344 7.137a.996.996 0 0 1 1.316.083l.71.71c.39.39.39 1.02 0 1.41l-.094.083A.996.996 0 0 1 4.96 9.34l-.71-.71a.996.996 0 0 1 0-1.41zM12 4l.1162.0068C12.612 4.0648 13 4.4893 13 5v1c0 .55-.44 1-1 1l-.1162-.0068C11.388 6.9352 11 6.5107 11 6V5c0-.55.45-1 1-1",
    },
  ],
  circles: [],
};

export const WbTwilightIcon = (props: IconProps) => renderIcon(props, iconType);
