/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M10.14 10.75l3 2.25V4h4v9h2V4c0-1.1-.9-2-2-2h-12c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h5v-2h-5V4h2v9l3-2.25z",
    },
    {
      d: "M19.37 15.79l-.63 2.87c-.15.71-.24 1.21-.28 1.5-.03-.22-.09-.56-.17-1.02-.08-.46-.17-.85-.25-1.2l-.49-2.16h-1.43l-.5 2.16c-.08.3-.16.68-.24 1.13-.08.45-.15.82-.18 1.08-.05-.38-.15-.88-.29-1.51l-.62-2.86H12.8l1.41 5.71h1.82c.33-1.5.52-2.35.57-2.56.05-.21.09-.44.14-.69.05-.25.08-.46.1-.63.03.21.07.47.12.78.05.31.1.52.12.62l.55 2.49h1.82l1.41-5.71h-1.49z",
    },
  ],
  circles: [],
};

export const BookProjectWfIcon = (props: IconProps) =>
  renderIcon(props, iconType);
