/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M12 2C6.4286 2 2 6.4286 2 12s4.4286 10 10 10 10-4.4286 10-10S17.5714 2 12 2m-.2223 9.7798h3.1301v4.0907q-.761.2483-1.4328.3481a9.3 9.3 0 0 1-1.3735.0999q-1.7863 0-2.728-1.0497t-.9418-3.0141q0-1.9106 1.0928-2.979 1.0929-1.0686 3.0303-1.0686 1.2144 0 2.3422.4857l-.5558 1.3384q-.8635-.4317-1.7972-.4317-1.0847 0-1.7377.7285t-.653 1.959q0 1.2846.5262 1.9618.526.6773 1.53.6773.5235 0 1.0631-.108v-1.646h-1.4949z",
      fillRule: "evenodd",
    },
  ],
  circles: [],
};

export const CountsTowardsGradeIcon = (props: IconProps) =>
  renderIcon(props, iconType);
