/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M12 2C6.4286 2 2 6.4286 2 12s4.4286 10 10 10 10-4.4286 10-10S17.5714 2 12 2m.6602 7.5995q-.9444 0-1.4625.7096-.5181.7098-.5181 1.978 0 2.639 1.9806 2.639.831 0 2.013-.4156v1.4032q-.9714.4048-2.1695.4048-1.7216 0-2.6336-1.0443t-.912-2.998q0-1.2305.4478-2.156.448-.9255 1.2872-1.4193t1.9671-.4938q1.1496 0 2.3098.5559l-.5396 1.36a9 9 0 0 0-.8905-.367q-.448-.1565-.8797-.1565",
      fillRule: "evenodd",
    },
  ],
  circles: [],
};

export const CreditNoCreditIcon = (props: IconProps) =>
  renderIcon(props, iconType);
