/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M12 2C6.4286 2 2 6.4286 2 12s4.4286 10 10 10 10-4.4286 10-10S17.5714 2 12 2m3.3288 10.19q0 1.9481-1.109 2.9843t-3.203 1.0362H8.7825v-7.89h2.4771q1.932 0 3.0006 1.02t1.0686 2.8494m-1.7378.043q0-2.5418-2.245-2.5418h-.8905v5.1377h.7178q2.4177 0 2.4177-2.5958",
      fillRule: "evenodd",
    },
  ],
  circles: [],
};

export const DroppedIcon = (props: IconProps) => renderIcon(props, iconType);
