/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M15.5 17H14l-2-7.5-2 7.5H8.5L6.1 7h1.7l1.54 7.5L11.3 7h1.4l1.97 7.5L16.2 7h1.7M19 3H5c-1.11 0-2 .89-2 2v14c0 1.1046.8954 2 2 2h14c1.1046 0 2-.8954 2-2V5c0-1.11-.9-2-2-2",
    },
  ],
  circles: [],
};

export const FileWordIcon = (props: IconProps) => renderIcon(props, iconType);
