/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M9.8 13.4h2.5c1.5 0 2.16-.28 2.8-.82.64-.55.9-1.33.9-2.35 0-.97-.25-1.73-.9-2.35-.65-.59-1.27-.88-2.8-.88H8v10h1.8zM19 3c1.1046 0 2 .8954 2 2v14c0 1.1046-.8954 2-2 2H5c-1.1046 0-2-.8954-2-2V5c0-1.11.9-2 2-2zm-9.2 9V8.4h2.3c.66 0 1.17.25 1.5.6s.5.72.5 1.24c0 .56-.18.95-.5 1.26s-.7.5-1.38.5z",
    },
  ],
  circles: [],
};

export const FilePowerpointIcon = (props: IconProps) =>
  renderIcon(props, iconType);
