/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M12 10.3125h1.125v3.375H12zm-5.625 1.125H7.5v-1.125H6.375zM21 5.25v13.5c0 1.2426-1.0074 2.25-2.25 2.25H5.25C4.0074 21 3 19.9926 3 18.75V5.25C3 4.0074 4.0074 3 5.25 3h13.5C19.9926 3 21 4.0074 21 5.25M9.1875 10.3125c0-.932-.7555-1.6875-1.6875-1.6875H4.6875v6.75H6.375v-2.25H7.5c.932 0 1.6875-.7555 1.6875-1.6875zm5.625 0c0-.932-.7555-1.6875-1.6875-1.6875h-2.8125v6.75h2.8125c.932 0 1.6875-.7555 1.6875-1.6875zm4.5-1.6875h-3.375v6.75h1.6875v-2.25h1.6875v-1.6875H17.625v-1.125h1.6875z",
    },
  ],
  circles: [],
};

export const FilePdfIcon = (props: IconProps) => renderIcon(props, iconType);
