/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M16.2 17h-2L12 13.2 9.8 17h-2l3.2-5-3.2-5h2l2.2 3.8L14.2 7h2L13 12m6-9H5c-1.11 0-2 .89-2 2v14c0 1.1046.8954 2 2 2h14c1.1046 0 2-.8954 2-2V5c0-1.11-.9-2-2-2",
    },
  ],
  circles: [],
};

export const FileExcelIcon = (props: IconProps) => renderIcon(props, iconType);
