/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M17.9982 2c1.1 0 2 .9 2 2v16c0 1.1-.9 2-2 2h-12c-1.1 0-2-.9-2-2L4 19H2.0001c-.0001-.5.0003.044 0-.7842V17H4l-.0019-2H2c0-.5.0004.044.0001-.7842L2 13h1.9981v-2H2c0-.2158.0004.044.0001-.7842L2 9h1.9981V7h-1.998c-.0001-.2158.0003.044 0-.7842L2 5h1.9981V4c0-1.1.9-2 2-2h12.0001zM8.0001 5.7158v4h8v-4h-8z",
    },
  ],
  circles: [],
};

export const NotebookIcon = (props: IconProps) => renderIcon(props, iconType);
