/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M12 2C6.4286 2 2 6.4286 2 12s4.4286 10 10 10 10-4.4286 10-10S17.5714 2 12 2m-1.0182 10.0334h.5505q.7717 0 1.1549-.305.3832-.3048.3832-.8877 0-.5883-.3211-.8689t-1.0065-.2806h-.761zm3.7778-1.252q0 1.2736-.796 1.9482t-2.264.6746h-.7178v2.8063h-1.673v-7.89h2.5203q1.4355 0 2.183.6178.7475.618.7475 1.843",
      fillRule: "evenodd",
    },
  ],
  circles: [],
};

export const PracticeIcon = (props: IconProps) => renderIcon(props, iconType);
