/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "m12.7692 20.0408 7.6923-4.1946V8.2015l-7.6923 2.8008zM12 9.6438l8.3892-3.053L12 3.5377l-8.3892 3.053zm10-3.0284v9.2308q0 .4208-.2162.7815-.216.3607-.5892.5646l-8.4615 4.6154Q12.396 22 12 22q-.3962 0-.733-.1923l-8.4616-4.6154q-.3723-.2046-.5892-.5646A1.48 1.48 0 0 1 2 15.8462V6.6154q0-.4807.2762-.8777c.2762-.397.4284-.4528.733-.5646l8.4616-3.077Q11.7354 2.0002 12 2q.2646 0 .5292.0962l8.4616 3.0769q.457.1685.733.5646c.276.396.2762.5567.2762.8777",
    },
  ],
  circles: [],
};

export const UnitIcon = (props: IconProps) => renderIcon(props, iconType);
