/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M1.4 2.81c.39-.39 1.02-.39 1.41 0l18.38 18.38c.39.39.39 1.03 0 1.42-.33.33-.84.36-1.22.13-.29.16-.61.26-.97.26h-6c-.55 0-1-.45-1-1s.45-1 1-1h5.17l-1-1H17c-1.1 0-2-.9-2-2v-.17L5.52 8.35C5.19 9.17 5 10.06 5 11v1h2c1.1 0 2 .9 2 2v4c0 1.1-.9 2-2 2H5c-1.1 0-2-.9-2-2v-7c0-1.5.37-2.91 1.02-4.15L1.39 4.22a.987.987 0 0 1 .01-1.41M12 2c4.97 0 9 4.03 9 9v7.17l-5.49-5.49c.36-.41.89-.68 1.49-.68h2v-1c0-3.87-3.13-7-7-7-1.47 0-2.83.45-3.95 1.23L6.62 3.8C8.12 2.67 9.98 2 12 2",
    },
  ],
  circles: [],
};

export const HeadsetOffIcon = (props: IconProps) => renderIcon(props, iconType);
