/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M19.5 6c.28 0 .5.22.5.5V7h1c.55 0 1 .45 1 1v9c0 .55-.45 1-1 1h-4c-.55 0-1-.45-1-1V8c0-.55.45-1 1-1h1v-.5c0-.28.22-.5.5-.5zM8 6c3.31 0 6 2.69 6 6v4c0 1.1-.9 2-2 2s-2-.9-2-2v-1c0-1.1.9-2 2-2h.5v-1c0-2.48-2.02-4.5-4.5-4.5S3.5 9.52 3.5 12v1H4c1.1 0 2 .9 2 2v1c0 1.1-.9 2-2 2s-2-.9-2-2v-4c0-3.31 2.69-6 6-6",
    },
  ],
  circles: [],
};

export const HeadphonesBatteryIcon = (props: IconProps) =>
  renderIcon(props, iconType);
