/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M20 20c1.1 0 2 .9 2 2s-.9 2-2 2H4c-1.1 0-2-.9-2-2s.9-2 2-2zM6.91.7C7.3.31 7.93.31 8.32.7l8.24 8.24c.59.59.59 1.54 0 2.12l-5.5 5.5c-.29.29-.68.44-1.06.44s-.77-.15-1.06-.44l-5.5-5.5c-.59-.58-.59-1.53 0-2.12l5.15-5.15-1.68-1.68a.9959.9959 0 010-1.41zM19 11.5s2 2.17 2 3.5c0 1.1-.9 2-2 2s-2-.9-2-2c0-1.33 2-3.5 2-3.5zm-9-6.29L5.21 10h9.58z",
    },
  ],
  circles: [],
};

export const FormatColorFillIcon = (props: IconProps) =>
  renderIcon(props, iconType);
