/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M14.06 6.19l3.75 3.75L6.89 20.85c-.09.1-.22.15-.35.15H3.5c-.28 0-.5-.22-.5-.5v-3.04c0-.14.05-.26.15-.36zm2.9-2.9c.39-.39 1.02-.39 1.41 0l2.34 2.34c.39.39.39 1.02 0 1.41l-1.83 1.83-3.75-3.75z",
    },
  ],
  circles: [],
};

export const ModeEditOutlineIcon = (props: IconProps) =>
  renderIcon(props, iconType);
