/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M12 2c5.52 0 10 4.48 10 10s-4.47 10-10 10S2 17.53 2 12 6.47 2 12 2zm0 2c-4.42 0-8 3.58-8 8s3.58 8 8 8 8-3.58 8-8-3.58-8-8-8zm0 4.5c.91 0 2.75.47 2.75 1.38V14c0 .28-.22.5-.5.5h-1v3.25c0 .69-.56 1.25-1.25 1.25s-1.25-.56-1.25-1.25V14.5h-1c-.28 0-.5-.22-.5-.5V9.88c0-.92 1.84-1.38 2.75-1.38zM12 5c.8284 0 1.5.6716 1.5 1.5S12.8284 8 12 8s-1.5-.6716-1.5-1.5S11.1716 5 12 5z",
    },
  ],
  circles: [],
};

export const AttributionIcon = (props: IconProps) =>
  renderIcon(props, iconType);
