/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M5 5h2v1c0 1.1.9 2 2 2h6c1.1 0 2-.9 2-2V5h2v5h2V5c0-1.1-.9-2-2-2h-4.18C14.4 1.84 13.3 1 12 1s-2.4.84-2.82 2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h6v-2H5zm15.25 7.25c.41-.41 1.09-.41 1.5 0s.41 1.09-.01 1.5l-5.53 5.54c-.39.39-1.02.39-1.41 0l-3.05-3.04c-.41-.41-.41-1.09 0-1.5l.1011-.0873c.4204-.3203 1.0204-.2912 1.3989.0873L15.51 17zM12 3c.55 0 1 .45 1 1s-.45 1-1 1-1-.45-1-1 .45-1 1-1z",
    },
  ],
  circles: [],
};

export const InventoryIcon = (props: IconProps) => renderIcon(props, iconType);
