/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M15.32 3c.26 0 .52.11.71.3l4.68 4.68c.18.18.29.44.28.7v6.64c0 .27-.1.52-.29.71l-4.68 4.68c-.19.18-.44.29-.71.29H8.68c-.26 0-.52-.11-.71-.3l-4.68-4.68c-.18-.19-.29-.44-.29-.71V8.68c0-.26.11-.52.29-.7l4.69-4.69c.18-.18.44-.29.7-.29zm-.42 2H9.1L5 9.1v5.8L9.1 19h5.8l4.1-4.1V9.1zM12 15c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1zm0-8c.55 0 1 .45 1 1v5c0 .55-.45 1-1 1s-1-.45-1-1V8c0-.55.45-1 1-1z",
    },
  ],
  circles: [],
};

export const ReportGmailerrorredIcon = (props: IconProps) =>
  renderIcon(props, iconType);
