/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M1.14 13.01c.47 0 .89.32.97.78.78 4.35 4.39 7.73 8.84 8.17v-1.74c0-.44.53-.67.85-.35l3.02 3c.29.29.13.76-.26.85-6.34 1.4-13.16-2.61-14.4-9.53-.11-.61.36-1.18.98-1.18zM14 6l1 1h1c1.1 0 2 .9 2 2v6c0 1.1-.9 2-2 2H8c-1.1 0-2-.9-2-2V9c0-1.1.9-2 2-2h1l1-1zm-2 4c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zM9.45.28c6.34-1.4 13.16 2.61 14.39 9.53.11.61-.36 1.18-.98 1.18-.47 0-.89-.32-.97-.78-.78-4.35-4.39-7.73-8.84-8.17v1.74c0 .44-.53.66-.85.35L9.19 1.12C8.9.84 9.05.36 9.45.28z",
    },
  ],
  circles: [],
};

export const CameraswitchIcon = (props: IconProps) =>
  renderIcon(props, iconType);
