/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M16 7c.55 0 1 .45 1 1s-.45 1-1 1h-5v6h4v-2h-1c-.55 0-1-.45-1-1s.45-1 1-1h2c.55 0 1 .45 1 1v3c0 1.1-.9 2-2 2h-4c-1.1 0-2-.9-2-2V9c0-1.1.9-2 2-2zM6 7c.55 0 1 .45 1 1v4c.55 0 1 .45 1 1s-.45 1-1 1v2c0 .55-.45 1-1 1s-1-.45-1-1v-2H2c-.55 0-1-.45-1-1V8c0-.55.45-1 1-1s1 .45 1 1v4h2V8c0-.55.45-1 1-1m15 2c.55 0 1 .45 1 1v1h1c.55 0 1 .45 1 1s-.45 1-1 1h-1v1c0 .55-.45 1-1 1s-1-.45-1-1v-1h-1c-.55 0-1-.45-1-1s.45-1 1-1h1v-1c0-.55.45-1 1-1",
    },
  ],
  circles: [],
};

export const Device4gPlusMobiledataIcon = (props: IconProps) =>
  renderIcon(props, iconType);
