/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M18 7v1l-2 3v9c0 1.1-.9 2-2 2h-4c-1.1 0-2-.9-2-2v-9L6 8V7zm-6 5.5c-.83 0-1.5.67-1.5 1.5s.67 1.5 1.5 1.5 1.5-.67 1.5-1.5-.67-1.5-1.5-1.5zM16 2c1.1 0 2 .9 2 2v1H6V4c0-1.1.9-2 2-2z",
    },
  ],
  circles: [],
};

export const FlashlightOnIcon = (props: IconProps) =>
  renderIcon(props, iconType);
