/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M2.194 3.427a.996.996 0 0 1 1.316.083l16.97 16.98c.39.39.39 1.02 0 1.41l-.094.083a.996.996 0 0 1-1.316-.083L16 18.83V20c0 1.1-.9 2-2 2h-4c-1.1 0-2-.9-2-2v-9.18l-5.9-5.9a.996.996 0 0 1 0-1.41zM18 7v1l-2 3v2.17L9.83 7zm-2-5c1.1 0 2 .9 2 2v1H7.83l-1.7-1.7C6.42 2.54 7.14 2 8 2z",
    },
  ],
  circles: [],
};

export const FlashlightOffIcon = (props: IconProps) =>
  renderIcon(props, iconType);
