/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M12 2c5.52 0 10 4.48 10 10s-4.48 10-10 10S2 17.52 2 12 6.48 2 12 2m0 4-.137.0065c-.5412.0515-.9992.4058-1.193.9135L7.33 15.8c-.22.58.21 1.2.83 1.2l.11-.007c.3258-.0421.612-.268.72-.583l.79-2.22h4.44l.78 2.22c.12.35.46.59.84.59l.1073-.0063c.561-.0665.9298-.6478.7227-1.1937l-3.34-8.88C13.12 6.37 12.59 6 12 6m.04 2.04 1.6 4.55h-3.29l1.6-4.55z",
    },
  ],
  circles: [],
};

export const HdrAutoIcon = (props: IconProps) => renderIcon(props, iconType);
