/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M17 6c1.1 0 2 .9 2 2v11c0 1.1-.9 2-2 2H7c-1.1 0-2-.9-2-2V8c0-1.1.9-2 2-2zm-5 3.5l-.1447.0069A1.4979 1.4979 0 0010.5 11v1h-1c-.83 0-1.5.67-1.5 1.5l.0069.1447A1.4979 1.4979 0 009.5 15h1v1c0 .83.67 1.5 1.5 1.5l.1447-.0069A1.4979 1.4979 0 0013.5 16v-1h1c.83 0 1.5-.67 1.5-1.5l-.0069-.1447A1.4979 1.4979 0 0014.5 12h-1v-1c0-.83-.67-1.5-1.5-1.5zM17 3c.55 0 1 .45 1 1l-.0068.1162C17.9352 4.612 17.5107 5 17 5H7c-.55 0-1-.45-1-1l.0068-.1162C6.0648 3.388 6.4893 3 7 3z",
    },
  ],
  circles: [],
};

export const MedicationIcon = (props: IconProps) => renderIcon(props, iconType);
