/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M2.194 3.427a.9959.9959 0 011.316.083l16.98 16.96c.39.39.39 1.02 0 1.41l-.094.083a.9959.9959 0 01-1.316-.083l-9.07-9.07v4.18h1.79c.44 0 .67.53.35.85l-2.79 2.79c-.2.19-.51.19-.71 0l-2.79-2.78c-.32-.31-.1-.85.35-.85H8v-6.18l-5.9-5.9a.9959.9959 0 010-1.41zM14.64 3.36c.2-.2.51-.2.71 0l2.79 2.79c.32.31.1.85-.35.85H16v6.17l-2-2V7h-1.79c-.45 0-.67-.54-.36-.85z",
    },
  ],
  circles: [],
};

export const MobiledataOffIcon = (props: IconProps) =>
  renderIcon(props, iconType);
