/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M10.59 2.59c.78-.79 2.05-.79 2.83 0L18 7.17v3.62l-6-6L4.79 12 12 19.2l6-6v3.62l-4.58 4.6c-.78.78-2.05.78-2.83 0l-8.01-8c-.78-.78-.78-2.05 0-2.83zM21 20c.5523 0 1 .4477 1 1s-.4477 1-1 1-1-.4477-1-1 .4477-1 1-1zm0-10l.1162.0068c.4958.058.8838.4825.8838.9932v6c0 .55-.45 1-1 1l-.1162-.0068C20.388 17.9352 20 17.5107 20 17v-6c0-.55.45-1 1-1zm-9.71-1.72c.39-.39 1.03-.39 1.41 0l3.01 3.01c.39.39.39 1.02 0 1.41l-3.01 3.01c-.39.39-1.02.39-1.41 0L8.28 12.7a.9959.9959 0 010-1.41z",
    },
  ],
  circles: [],
};

export const NearbyErrorIcon = (props: IconProps) =>
  renderIcon(props, iconType);
