/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M18.88 13.22c.39-.39 1.02-.39 1.42 0l.083.094a.9959.9959 0 01-.083 1.316l-5.66 5.66c-.39.39-1.02.39-1.41 0l-2.83-2.83a.9959.9959 0 010-1.41l.094-.083a.9959.9959 0 011.316.083l2.12 2.12zM7.5 3c.55 0 1 .45 1 1H10c.55 0 1 .45 1 1s-.45 1-1 1H6v2h4c.55 0 1 .45 1 1v4c0 .55-.45 1-1 1H8.5c0 .55-.45 1-1 1s-1-.45-1-1H5c-.55 0-1-.45-1-1s.45-1 1-1h4v-2H5c-.55 0-1-.45-1-1V5c0-.55.45-1 1-1h1.5c0-.55.45-1 1-1z",
    },
  ],
  circles: [],
};

export const PriceCheckIcon = (props: IconProps) => renderIcon(props, iconType);
