/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M22 19c.55 0 1 .45 1 1s-.45 1-1 1H2c-.55 0-1-.45-1-1s.45-1 1-1zM20 3c1.1 0 2 .9 2 2l-.01 11c0 1.1-.89 2-1.99 2H4c-1.1 0-2-.9-2-2V5c0-1.1.9-2 2-2zm-6.03 4.53c-1.52-1.53-4.1-1.35-5.38.52-.76 1.12-.8 2.65-.07 3.79 1.11 1.75 3.3 2.11 4.87 1.11l1.55 1.55c.29.29.77.29 1.06 0s.29-.77 0-1.06l-1.56-1.55c.87-1.36.71-3.18-.47-4.36zM11.5 8c1.1046 0 2 .8954 2 2s-.8954 2-2 2-2-.8954-2-2 .8954-2 2-2z",
    },
  ],
  circles: [],
};

export const ScreenSearchDesktopIcon = (props: IconProps) =>
  renderIcon(props, iconType);
