/******************************************************
 * This file was created by scripts/generate.js as part
 * of the build process. Do not edit this file directly.
 ******************************************************/

import { IconProps } from "../../IconProps";
import { renderIcon } from "../../SvgIcon";
const iconType = {
  viewBox: "0 0 24 24",
  paths: [
    {
      d: "M17 1.01 7 1c-1.1 0-2 .9-2 2v18c0 1.1.9 2 2 2h10c1.1 0 2-.9 2-2V3c0-1.1-.9-1.99-2-1.99M17 18H7V6h10zm-6.66-3.71c.39.39 1.02.39 1.41 0l3.54-3.54c.39-.39.39-1.02 0-1.41s-1.02-.39-1.41 0l-2.83 2.83-.71-.71c-.39-.39-1.02-.39-1.41 0s-.39 1.02 0 1.41z",
    },
  ],
  circles: [],
};

export const SystemSecurityUpdateGoodIcon = (props: IconProps) =>
  renderIcon(props, iconType);
